# Generated by Django 5.1.3 on 2024-12-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
